// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :many
WITH inserted_feed_follow AS (
    INSERT INTO feed_follows (id, created_at, updated_at, user_id, feed_id)
    VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
    )
    RETURNING id, created_at, updated_at, user_id, feed_id
    )
SELECT
    inserted_feed_follow.id, inserted_feed_follow.created_at, inserted_feed_follow.updated_at, inserted_feed_follow.user_id, inserted_feed_follow.feed_id,
    feeds.name AS feed_name,
    followers.name AS user_name,
    creators.name AS creator_name
FROM inserted_feed_follow
INNER JOIN feeds ON inserted_feed_follow.feed_id = feeds.id
INNER JOIN users AS followers ON inserted_feed_follow.user_id = followers.id
INNER JOIN users AS creators ON feeds.user_id = creators.id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type CreateFeedFollowRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
	FeedID      uuid.UUID
	FeedName    string
	UserName    string
	CreatorName string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) ([]CreateFeedFollowRow, error) {
	rows, err := q.db.QueryContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateFeedFollowRow
	for rows.Next() {
		var i CreateFeedFollowRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
			&i.FeedName,
			&i.UserName,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedFollow = `-- name: GetFeedFollow :one
SELECT 
    feed_follows.id, feed_follows.created_at, feed_follows.updated_at, feed_follows.user_id, feed_id, feeds.id, feeds.created_at, feeds.updated_at, feeds.name, url, feeds.user_id, followers.id, followers.created_at, followers.updated_at, followers.name, creators.id, creators.created_at, creators.updated_at, creators.name,
    feeds.name AS feed_name,
    followers.name AS user_name,
    creators.name AS creator_name
FROM feed_follows
INNER JOIN feeds ON feed_follows.feed_id = feeds.id
INNER JOIN users AS followers ON feed_follows.user_id = followers.id
INNER JOIN users AS creators ON feeds.user_id = creators.id
WHERE
    feeds.url = $1
`

type GetFeedFollowRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
	FeedID      uuid.UUID
	ID_2        uuid.UUID
	CreatedAt_2 time.Time
	UpdatedAt_2 time.Time
	Name        string
	Url         string
	UserID_2    uuid.UUID
	ID_3        uuid.UUID
	CreatedAt_3 time.Time
	UpdatedAt_3 time.Time
	Name_2      string
	ID_4        uuid.UUID
	CreatedAt_4 time.Time
	UpdatedAt_4 time.Time
	Name_3      string
	FeedName    string
	UserName    string
	CreatorName string
}

func (q *Queries) GetFeedFollow(ctx context.Context, url string) (GetFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, getFeedFollow, url)
	var i GetFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.ID_2,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.Name,
		&i.Url,
		&i.UserID_2,
		&i.ID_3,
		&i.CreatedAt_3,
		&i.UpdatedAt_3,
		&i.Name_2,
		&i.ID_4,
		&i.CreatedAt_4,
		&i.UpdatedAt_4,
		&i.Name_3,
		&i.FeedName,
		&i.UserName,
		&i.CreatorName,
	)
	return i, err
}

const getFeedFollowForUser = `-- name: GetFeedFollowForUser :many
SELECT
    feed_follows.id, feed_follows.created_at, feed_follows.updated_at, feed_follows.user_id, feed_id, feeds.id, feeds.created_at, feeds.updated_at, feeds.name, url, feeds.user_id, followers.id, followers.created_at, followers.updated_at, followers.name, creators.id, creators.created_at, creators.updated_at, creators.name,
    feeds.name AS feed_name,
    followers.name AS user_name,
    creators.name AS creator_name
FROM feed_follows
INNER JOIN feeds ON feed_follows.feed_id = feeds.id
INNER JOIN users AS followers ON feed_follows.user_id = followers.id
INNER JOIN users AS creators ON feeds.user_id = creators.id
WHERE
    followers.name = $1
`

type GetFeedFollowForUserRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
	FeedID      uuid.UUID
	ID_2        uuid.UUID
	CreatedAt_2 time.Time
	UpdatedAt_2 time.Time
	Name        string
	Url         string
	UserID_2    uuid.UUID
	ID_3        uuid.UUID
	CreatedAt_3 time.Time
	UpdatedAt_3 time.Time
	Name_2      string
	ID_4        uuid.UUID
	CreatedAt_4 time.Time
	UpdatedAt_4 time.Time
	Name_3      string
	FeedName    string
	UserName    string
	CreatorName string
}

func (q *Queries) GetFeedFollowForUser(ctx context.Context, name string) ([]GetFeedFollowForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowForUser, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowForUserRow
	for rows.Next() {
		var i GetFeedFollowForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
			&i.ID_2,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.Name,
			&i.Url,
			&i.UserID_2,
			&i.ID_3,
			&i.CreatedAt_3,
			&i.UpdatedAt_3,
			&i.Name_2,
			&i.ID_4,
			&i.CreatedAt_4,
			&i.UpdatedAt_4,
			&i.Name_3,
			&i.FeedName,
			&i.UserName,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
